import type { Job, Resource, Task } from "./types";

// In-memory store for jobs (shared across API routes in the same server process)
export const resources: Resource[] = [
  { id: 1, name: "John Doe", type: "Human" },
  { id: 2, name: "Sarah Johnson", type: "Human" },
  { id: 3, name: "Mike Chen", type: "Human" },
  { id: 4, name: "David Martinez", type: "Human" },
  { id: 5, name: "Emma Williams", type: "Human" },
  { id: 6, name: "Alex Turner", type: "Human" },
  { id: 7, name: "Lisa Park", type: "Human" },
  { id: 8, name: "Tower Crane TC-200", type: "Equipment" },
  { id: 9, name: "Excavator CAT 320", type: "Equipment" },
  { id: 10, name: "Concrete Mixer CM-50", type: "Equipment" },
  { id: 11, name: "Bulldozer D6", type: "Equipment" },
  { id: 12, name: "Scaffolding Set A", type: "Equipment" },
  { id: 13, name: "Welding Machine WM-300", type: "Equipment" },
  { id: 14, name: "Dump Truck DT-10", type: "Equipment" },
];

export const tasksList: Task[] = [
  { id: 1, title: "Foundation Excavation", project: "Downtown Office Complex" },
  { id: 2, title: "Steel Frame Installation", project: "Downtown Office Complex" },
  { id: 3, title: "Concrete Pour - Floor 3", project: "Residential Tower A" },
  { id: 4, title: "Electrical Wiring - Phase 1", project: "Residential Tower A" },
  { id: 5, title: "HVAC System Installation", project: "Shopping Center Renovation" },
  { id: 6, title: "Demolition - East Wing", project: "Shopping Center Renovation" },
  { id: 7, title: "Final Inspection", project: "Highway Expansion Project" },
  { id: 8, title: "Medical Equipment Installation", project: "Hospital Wing Extension" },
  { id: 9, title: "Paint & Finishing - Level 2", project: "Downtown Office Complex" },
  { id: 10, title: "Safety Inspection", project: "Hospital Wing Extension" },
];

export const jobsStore: Job[] = [
  {
    id: 1,
    title: "Site Preparation",
    description: "Prepare the site for foundation excavation including clearing and grading",
    taskId: 1,
    taskName: "Foundation Excavation",
    startDate: "2025-01-10",
    endDate: "2025-01-25",
    status: "Completed",
    assignedHumans: [1, 3],
    assignedEquipment: [9, 11],
  },
  {
    id: 2,
    title: "Beam Delivery Coordination",
    description: "Coordinate the delivery and staging of steel beams for frame installation",
    taskId: 2,
    taskName: "Steel Frame Installation",
    startDate: "2025-02-01",
    endDate: "2025-02-15",
    status: "Completed",
    assignedHumans: [2],
    assignedEquipment: [8, 14],
  },
  {
    id: 3,
    title: "Crane Setup & Testing",
    description: "Set up and test the tower crane for steel frame lifting operations",
    taskId: 2,
    taskName: "Steel Frame Installation",
    startDate: "2025-02-10",
    endDate: "2025-02-20",
    status: "In Progress",
    assignedHumans: [2, 6],
    assignedEquipment: [8],
  },
  {
    id: 4,
    title: "Rebar Placement",
    description: "Place rebar reinforcement for the third floor concrete pour",
    taskId: 3,
    taskName: "Concrete Pour - Floor 3",
    startDate: "2025-02-15",
    endDate: "2025-03-01",
    status: "In Progress",
    assignedHumans: [3, 7],
    assignedEquipment: [10, 12],
  },
  {
    id: 5,
    title: "Conduit Installation",
    description: "Install electrical conduit runs throughout the first phase area",
    taskId: 4,
    taskName: "Electrical Wiring - Phase 1",
    startDate: "2025-03-01",
    endDate: "2025-03-20",
    status: "In Progress",
    assignedHumans: [4],
    assignedEquipment: [13],
  },
  {
    id: 6,
    title: "Ductwork Design Review",
    description: "Review and finalize HVAC ductwork designs before procurement",
    taskId: 5,
    taskName: "HVAC System Installation",
    startDate: "2025-04-01",
    endDate: "2025-04-10",
    status: "Planning",
    assignedHumans: [1, 5],
    assignedEquipment: [],
  },
  {
    id: 7,
    title: "Hazmat Inspection",
    description: "Conduct hazardous material inspection before demolition begins",
    taskId: 6,
    taskName: "Demolition - East Wing",
    startDate: "2025-03-15",
    endDate: "2025-03-25",
    status: "Planning",
    assignedHumans: [5],
    assignedEquipment: [9, 11],
  },
  {
    id: 8,
    title: "Equipment Delivery",
    description: "Coordinate medical equipment delivery and staging at hospital wing",
    taskId: 8,
    taskName: "Medical Equipment Installation",
    startDate: "2025-03-10",
    endDate: "2025-03-30",
    status: "In Progress",
    assignedHumans: [3, 6],
    assignedEquipment: [14],
  },
  {
    id: 9,
    title: "Surface Preparation",
    description: "Sand and prepare all surfaces on level 2 for painting",
    taskId: 9,
    taskName: "Paint & Finishing - Level 2",
    startDate: "2025-02-20",
    endDate: "2025-03-05",
    status: "Completed",
    assignedHumans: [4, 7],
    assignedEquipment: [12],
  },
  {
    id: 10,
    title: "Safety Protocols Review",
    description: "Review all safety protocols and documentation for hospital wing inspection",
    taskId: 10,
    taskName: "Safety Inspection",
    startDate: "2025-02-10",
    endDate: "2025-02-28",
    status: "On Hold",
    assignedHumans: [1],
    assignedEquipment: [],
  },
];

let nextId = 11;

export function getNextId() {
  return nextId++;
}
